import type { Metadata } from "next";
import { Inconsolata } from "next/font/google"
import "./globals.css";
import Topbar from "@/components/topbar";
import { ThemeProvider } from "@/context/theme-context";

const inconsolata = Inconsolata({
  variable: "--inconsolata",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inconsolata.className}`}>
        <ThemeProvider>
          <Topbar />
          {children}
        </ThemeProvider>
      </body>
    </html >
  );
}
